; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Sistema Pregações"
#define MyAppVersion "1.5"
#define MyAppPublisher "Religião de Deus"
#define MyAppURL "www.religiaodedeus.org"
#define MyAppExeName "SysPregacoes.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7D385850-8BA7-4037-968F-3DD427479B60}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=c:\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=C:\Users\amtho\Desktop
OutputBaseFilename=Sistema Pregações
SetupIconFile=C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\Icones\mic_foam_brightblue_icon-icons.com_52614.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\SysPregacoes.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\CamadaApresentacao\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\CamadaDados\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\CamadaNegocio\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\CamadaApresentacao.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\CamadaApresentacao.dll.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\CamadaApresentacao.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\CamadaDados.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\CamadaDados.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\CamadaNegocio.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\CamadaNegocio.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\EnvDTE.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.MSXML.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.ReportViewer.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.ReportViewer.DataVisualization.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.ReportViewer.Design.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.ReportViewer.ProcessingObjectModel.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.ReportViewer.WebDesign.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.ReportViewer.WebForms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.ReportViewer.WinForms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.SqlServer.Types.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.VisualStudio.OLE.Interop.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.VisualStudio.Shell.Interop.8.0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.VisualStudio.Shell.Interop.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.VisualStudio.TextManager.Interop.8.0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\Microsoft.VisualStudio.TextManager.Interop.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\SysPregacoes\bin\Debug\stdole.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\amtho\Desktop\Projeto Pregacoes\SysPregacoes\CamadaApresentacao\Pregações.rdlc"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

